included:
  - Sources
line_length:
  warning: 150
  error: 175
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ### works up until this config rule
  ignores_interpolated_strings: true
function_body_length:
  warning: 75
  error: 125
