osx_image: xcode10.2
language: objective-c

script:
  - set -o pipefail && xcodebuild -project Syncalicious.xcodeproj -scheme "Syncalicious" -sdk macosx clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED="NO" | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
